### ISSUE TITLE
New version does not work

### ISSUE THREAD

**Issue by vnwr** [Nowaha/WebSwimming#1]
The new version of WebSwimming (1.0.2) does not work, and respawns you when you hit the water like it would if the mod was not installed. The issue was fixed for me by downgrading to the previous version (1.0.1) in Hook, Line, & Sinker. 

WEBFISHING Version: 1.08
HLS Version: 1.2.4
OS: Windows 10 2019 Enterprise LTSC

**Comment by Nowaha** [comment]
1.0.2 only changes the store page, I didn't touch the mod itself. Extracting the zip seems to show the right files. Are you sure it is installed properly and still doesn't work?
